version: '3.8'
#чутка шарю в этой теме
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    
  api:
    build: .
    ports:
      - "5192:8080" #порт локальный:контейнера
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_CONNECTION_STRING=redis:6379
    env_file:
      - .env
    depends_on:
      - redis
