// <auto-generated />
using FilmsArchive.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FilmsArchive.Migrations
{
    [DbContext(typeof(postgresContext))]
    [Migration("20260330185544_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FilmsArchive.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Birthyear")
                        .HasColumnType("integer")
                        .HasColumnName("birthyear");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("FilmsArchive.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genre");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("FilmsArchive.Models.Movieactor", b =>
                {
                    b.Property<int>("Movieid")
                        .HasColumnType("integer")
                        .HasColumnName("movieid");

                    b.Property<int>("Actorid")
                        .HasColumnType("integer")
                        .HasColumnName("actorid");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role");

                    b.HasKey("Movieid", "Actorid")
                        .HasName("movieactors_pkey");

                    b.HasIndex(new[] { "Actorid" }, "idx_movieactors_actorid");

                    b.HasIndex(new[] { "Movieid" }, "idx_movieactors_movieid");

                    b.ToTable("movieactors", (string)null);
                });

            modelBuilder.Entity("FilmsArchive.Models.Movieactor", b =>
                {
                    b.HasOne("FilmsArchive.Models.Actor", "Actor")
                        .WithMany("Movieactors")
                        .HasForeignKey("Actorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movieactors_actorid_fkey");

                    b.HasOne("FilmsArchive.Models.Movie", "Movie")
                        .WithMany("Movieactors")
                        .HasForeignKey("Movieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movieactors_movieid_fkey");

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("FilmsArchive.Models.Actor", b =>
                {
                    b.Navigation("Movieactors");
                });

            modelBuilder.Entity("FilmsArchive.Models.Movie", b =>
                {
                    b.Navigation("Movieactors");
                });
#pragma warning restore 612, 618
        }
    }
}
